### ISSUE TITLE
Wrong path for images

### ISSUE THREAD

**Issue by Gabbalo** [acaranta/tt-rss-yourls#4]
Hi,

I just installed the YOURLS plugin and it works just fine ... exept the images of tweetshare and fbshare aren't displayed properly.
![image](https://cloud.githubusercontent.com/assets/5897819/13026424/d32b5872-d227-11e5-96ff-b4a52c1ceacf.png)
They are stored in the plugin-directory, but the call in the code ist not goint there.

https://short.domain.tld/plugins/yourls/tweetshare.png <-- in the code (/plugins/yourls/tweetshare.png, to be exactly :) )
https://short.domain.tld/tt-rss/plugins/yourls/tweetshare.png <- actual path

Somehow, the path to the directory of the plugin is not read properly.

Greets, Gabba

**Comment by acaranta** [comment]
Can you check if #8 (merged a few seconds ago) corrects this problem ? :p

**Comment by matecode** [comment]
This does not correct the problem because the path to the image is hardcoded in js file. The slash in the beginning cuts of the directory.
